service: dna-mutations

plugins:
  - serverless-dotenv-plugin
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-ssm-fetch

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  environment:
    NODE_ENV: ${self:custom.nodeEnv.${opt:stage, self:provider.stage}}
    NODE_PATH: ./src

custom:
  nodeEnv:
    dev: development
    prod: production
  serverlessSsmFetch:
    DB_CONNECTION_STRING: /apps/dna-mutations/db_connection_string
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true # Execute all the migration upon DynamoDB Local Start.

functions:
  hasMutation:
    handler: src/interfaces/http/handlers/mutation.hasMutationHandler
    events:
      - http:
          path: /mutation
          method: post

  stats:
    handler: src/interfaces/http/handlers/stats.statsHandler
    events:
      - http:
          path: /stats
          method: get

resources:
  Resources: ${file(migrations/mutation.yml)}
